Program Ths;

{$I Ths.inc}

uses
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  System.StartUpCopy,
  System.Classes,
  System.SysUtils,
  System.IOUtils,
  Winapi.Messages,
  Winapi.Windows,
  udm in 'BackEnd\Core\udm.pas' {dm: TDataModule},
  SynCommons in 'BackEnd\Tools\SynPDF\SynCommons.pas',
  SynLZ in 'BackEnd\Tools\SynPDF\SynLZ.pas',
  SynPdf in 'BackEnd\Tools\SynPDF\SynPdf.pas',
  SynGdiPlus in 'BackEnd\Tools\SynPDF\SynGdiPlus.pas',
  SynZip in 'BackEnd\Tools\SynPDF\SynZip.pas',
  SynTable in 'BackEnd\Tools\SynPDF\SynTable.pas',
  SynCrypto in 'BackEnd\Tools\SynPDF\SynCrypto.pas',
  mORMotReport in 'BackEnd\Tools\SynPDF\mORMotReport.pas',
  Bcrypt in 'Utils\Bcrypt.pas',
  Ths.Helper.BaseTypes in 'BackEnd\Tools\Ths.Helper.BaseTypes.pas',
  Ths.Helper.Button in 'BackEnd\Tools\Ths.Helper.Button.pas',
  Ths.Helper.ComboBox in 'BackEnd\Tools\Ths.Helper.ComboBox.pas',
  Ths.Helper.CustomFileDialog in 'BackEnd\Tools\Ths.Helper.CustomFileDialog.pas',
  Ths.Helper.Edit in 'BackEnd\Tools\Ths.Helper.Edit.pas',
  Ths.Helper.Memo in 'BackEnd\Tools\Ths.Helper.Memo.pas',
  Ths.Helper.SpinEdit in 'BackEnd\Tools\Ths.Helper.SpinEdit.pas',
  Ths.Helper.StringGrid in 'BackEnd\Tools\Ths.Helper.StringGrid.pas',
  Ths.Helper.ThsList in 'BackEnd\Tools\Ths.Helper.ThsList.pas',
  Ths.Utils.Images in 'BackEnd\Tools\Ths.Utils.Images.pas',
  Ths.DialogHelper in 'BackEnd\Tools\Ths.DialogHelper.pas',
  Ths.Database.Connection.Settings in 'BackEnd\Core\Ths.Database.Connection.Settings.pas',
  Ths.Globals in 'BackEnd\Core\Ths.Globals.pas',
  Ths.Constants in 'BackEnd\Core\Ths.Constants.pas',
  ufrmBase in 'Forms\Core\Base\ufrmBase.pas' {frmBase},
  ufrmAbout in 'Forms\Core\Input\ufrmAbout.pas' {frmAbout},
  ufrmCalculator in 'Forms\Core\Input\ufrmCalculator.pas' {frmCalculator},
  ufrmConfirmation in 'Forms\Core\Input\ufrmConfirmation.pas' {frmConfirmation},
  ufrmLogin in 'Forms\Core\Input\ufrmLogin.pas' {frmLogin},
  ufrmDashboard in 'Forms\Core\Input\ufrmDashboard.pas' {frmDashboard},
  Logger in 'BackEnd\Core\Logger.pas',
  SharedFormTypes in 'BackEnd\Core\Base\SharedFormTypes.pas',
  EntityAttributes in 'BackEnd\Core\Base\EntityAttributes.pas',
  Entity in 'BackEnd\Core\Base\Entity.pas',
  FilterCriterion in 'BackEnd\Core\Base\FilterCriterion.pas',
  LocalizationManager in 'BackEnd\Core\Base\LocalizationManager.pas',
  ConnectionManager in 'BackEnd\Core\Base\ConnectionManager.pas',
  Repository in 'BackEnd\Core\Base\Repository.pas',
  Service in 'BackEnd\Core\Base\Service.pas',
  UnitOfWork in 'BackEnd\Core\Base\UnitOfWork.pas',
  EntitySchemaCache in 'BackEnd\Core\Base\EntitySchemaCache.pas',
  MetaProvider in 'BackEnd\Core\MetaProvider.pas',
  Password.Helper in 'BackEnd\Core\Base\Password.Helper.pas',
  AppContext in 'BackEnd\Core\AppContext.pas',
  UserContext in 'BackEnd\Core\UserContext.pas',
  ufrmGrid in 'Forms\Core\Base\ufrmGrid.pas',
  ufrmInputSimpleDB in 'Forms\Core\Base\ufrmInputSimpleDB.pas',
  Auth.Service in 'BackEnd\Core\Auth.Service.pas',
  SysAccessRight in 'BackEnd\System\Domain\SysAccessRight.pas',
  SysAccessRight.Exception in 'BackEnd\System\Exception\SysAccessRight.Exception.pas',
  SysAccessRight.Repository in 'BackEnd\System\Repository\SysAccessRight.Repository.pas',
  SysAccessRight.Service in 'BackEnd\System\Service\SysAccessRight.Service.pas',
  ufrmSysAccessRight in 'Forms\System\Input\ufrmSysAccessRight.pas' {frmSysAccessRight},
  ufrmSysAccessRights in 'Forms\System\Output\ufrmSysAccessRights.pas' {frmSysAccessRights},
  SysAddress in 'BackEnd\System\Domain\SysAddress.pas',
  SysAddress.Repository in 'BackEnd\System\Repository\SysAddress.Repository.pas',
  SysAddress.Service in 'BackEnd\System\Service\SysAddress.Service.pas',
  ufrmSysAddress in 'Forms\System\Input\ufrmSysAddress.pas' {frmSysAddress},
  ufrmSysAddresses in 'Forms\System\Output\ufrmSysAddresses.pas' {frmSysAddresses},
  SysApplicationSetting in 'BackEnd\System\Domain\SysApplicationSetting.pas',
  SysApplicationSetting.Repository in 'BackEnd\System\Repository\SysApplicationSetting.Repository.pas',
  SysApplicationSetting.Service in 'BackEnd\System\Service\SysApplicationSetting.Service.pas',
  ufrmSysApplicationSetting in 'Forms\System\Input\ufrmSysApplicationSetting.pas' {frmSysApplicationSetting},
  SysCity in 'BackEnd\System\Domain\SysCity.pas',
  SysCity.Repository in 'BackEnd\System\Repository\SysCity.Repository.pas',
  SysCity.Service in 'BackEnd\System\Service\SysCity.Service.pas',
  ufrmSysCity in 'Forms\System\Input\ufrmSysCity.pas' {frmSysCity},
  ufrmSysCities in 'Forms\System\Output\ufrmSysCities.pas' {frmSysCities},
  SysCountry in 'BackEnd\System\Domain\SysCountry.pas',
  SysCountry.Repository in 'BackEnd\System\Repository\SysCountry.Repository.pas',
  SysCountry.Service in 'BackEnd\System\Service\SysCountry.Service.pas',
  ufrmSysCountry in 'Forms\System\Input\ufrmSysCountry.pas' {frmSysCountry},
  ufrmSysCountries in 'Forms\System\Output\ufrmSysCountries.pas' {frmSysCountries},
  SysCurrency in 'BackEnd\System\Domain\SysCurrency.pas',
  SysCurrency.Repository in 'BackEnd\System\Repository\SysCurrency.Repository.pas',
  SysCurrency.Service in 'BackEnd\System\Service\SysCurrency.Service.pas',
  ufrmSysCurrency in 'Forms\System\Input\ufrmSysCurrency.pas' {frmSysCurrency},
  ufrmSysCurrencies in 'Forms\System\Output\ufrmSysCurrencies.pas' {frmSysCurrencies},
  SysDecimalPlace in 'BackEnd\System\Domain\SysDecimalPlace.pas',
  SysDecimalPlace.Repository in 'BackEnd\System\Repository\SysDecimalPlace.Repository.pas',
  SysDecimalPlace.Service in 'BackEnd\System\Service\SysDecimalPlace.Service.pas',
  ufrmSysDecimalPlace in 'Forms\System\Input\ufrmSysDecimalPlace.pas' {frmSysDecimalPlace},
  ufrmSysDecimalPlaces in 'Forms\System\Output\ufrmSysDecimalPlaces.pas' {frmSysDecimalPlaces},
  SysGridColumn in 'BackEnd\System\Domain\SysGridColumn.pas',
  SysGridColumn.Repository in 'BackEnd\System\Repository\SysGridColumn.Repository.pas',
  SysGridColumn.Service in 'BackEnd\System\Service\SysGridColumn.Service.pas',
  ufrmSysGridColumn in 'Forms\System\Input\ufrmSysGridColumn.pas' {frmSysGridColumn},
  ufrmSysGridColumns in 'Forms\System\Output\ufrmSysGridColumns.pas' {frmSysGridColumns},
  SysGridFilter in 'BackEnd\System\Domain\SysGridFilter.pas',
  SysGridFilter.Repository in 'BackEnd\System\Repository\SysGridFilter.Repository.pas',
  SysGridFilter.Service in 'BackEnd\System\Service\SysGridFilter.Service.pas',
  ufrmSysGridFilter in 'Forms\System\Input\ufrmSysGridFilter.pas' {frmSysGridFilter},
  ufrmSysGridFilters in 'Forms\System\Output\ufrmSysGridFilters.pas' {frmSysGridFilters},
  SysGridSort in 'BackEnd\System\Domain\SysGridSort.pas',
  SysGridSort.Repository in 'BackEnd\System\Repository\SysGridSort.Repository.pas',
  SysGridSort.Service in 'BackEnd\System\Service\SysGridSort.Service.pas',
  ufrmSysGridSort in 'Forms\System\Input\ufrmSysGridSort.pas' {frmSysGridSort},
  ufrmSysGridSorts in 'Forms\System\Output\ufrmSysGridSorts.pas' {frmSysGridSorts},
  SysLanguage in 'BackEnd\System\Domain\SysLanguage.pas',
  SysLanguage.Repository in 'BackEnd\System\Repository\SysLanguage.Repository.pas',
  SysLanguage.Service in 'BackEnd\System\Service\SysLanguage.Service.pas',
  ufrmSysLanguage in 'Forms\System\Input\ufrmSysLanguage.pas' {frmSysLanguage},
  ufrmSysLanguages in 'Forms\System\Output\ufrmSysLanguages.pas' {frmSysLanguages},
  SysPermission in 'BackEnd\System\Domain\SysPermission.pas',
  SysPermission.Repository in 'BackEnd\System\Repository\SysPermission.Repository.pas',
  SysPermission.Service in 'BackEnd\System\Service\SysPermission.Service.pas',
  ufrmSysPermission in 'Forms\System\Input\ufrmSysPermission.pas' {frmSysPermission},
  ufrmSysPermissions in 'Forms\System\Output\ufrmSysPermissions.pas' {frmSysPermissions},
  SysPermissionGroup in 'BackEnd\System\Domain\SysPermissionGroup.pas',
  SysPermissionGroup.Repository in 'BackEnd\System\Repository\SysPermissionGroup.Repository.pas',
  SysPermissionGroup.Service in 'BackEnd\System\Service\SysPermissionGroup.Service.pas',
  ufrmSysPermissionGroup in 'Forms\System\Input\ufrmSysPermissionGroup.pas' {frmSysPermissionGroup},
  ufrmSysPermissionGroups in 'Forms\System\Output\ufrmSysPermissionGroups.pas' {frmSysPermissionGroups},
  SysRegion in 'BackEnd\System\Domain\SysRegion.pas',
  SysRegion.Repository in 'BackEnd\System\Repository\SysRegion.Repository.pas',
  SysRegion.Service in 'BackEnd\System\Service\SysRegion.Service.pas',
  ufrmSysRegion in 'Forms\System\Input\ufrmSysRegion.pas' {frmSysRegion},
  ufrmSysRegions in 'Forms\System\Output\ufrmSysRegions.pas' {frmSysRegions},
  SysUom in 'BackEnd\System\Domain\SysUom.pas',
  SysUom.Repository in 'BackEnd\System\Repository\SysUom.Repository.pas',
  SysUom.Service in 'BackEnd\System\Service\SysUom.Service.pas',
  ufrmSysUom in 'Forms\System\Input\ufrmSysUom.pas' {frmSysUom},
  ufrmSysUoms in 'Forms\System\Output\ufrmSysUoms.pas' {frmSysUoms},
  SysUomGroup in 'BackEnd\System\Domain\SysUomGroup.pas',
  SysUomGroup.Repository in 'BackEnd\System\Repository\SysUomGroup.Repository.pas',
  SysUomGroup.Service in 'BackEnd\System\Service\SysUomGroup.Service.pas',
  ufrmSysUomGroup in 'Forms\System\Input\ufrmSysUomGroup.pas' {frmSysUomType},
  ufrmSysUomGroups in 'Forms\System\Output\ufrmSysUomGroups.pas' {frmSysUomTypes},
  SysUser in 'BackEnd\System\Domain\SysUser.pas',
  SysUser.Repository in 'BackEnd\System\Repository\SysUser.Repository.pas',
  SysUser.Service in 'BackEnd\System\Service\SysUser.Service.pas',
  ufrmSysUser in 'Forms\System\Input\ufrmSysUser.pas' {frmSysUser},
  ufrmSysUsers in 'Forms\System\Output\ufrmSysUsers.pas' {frmSysUsers},
  EmpPerson in 'BackEnd\Employee\Domain\EmpPerson.pas',
  EmpPerson.Repository in 'BackEnd\Employee\Repository\EmpPerson.Repository.pas',
  EmpPerson.Service in 'BackEnd\Employee\Service\EmpPerson.Service.pas',
  ufrmEmpPerson in 'Forms\Employee\Input\ufrmEmpPerson.pas' {frmEmpPerson},
  ufrmEmpPersons in 'Forms\Employee\Output\ufrmEmpPersons.pas' {frmEmpPersons},
  EmpPersonType in 'BackEnd\Employee\Domain\EmpPersonType.pas',
  EmpPersonType.Repository in 'BackEnd\Employee\Repository\EmpPersonType.Repository.pas',
  EmpPersonType.Service in 'BackEnd\Employee\Service\EmpPersonType.Service.pas',
  ufrmEmpPersonType in 'Forms\Employee\Input\ufrmEmpPersonType.pas' {frmEmpPersonType},
  ufrmEmpPersonTypes in 'Forms\Employee\Output\ufrmEmpPersonTypes.pas' {frmEmpPersonTypes},
  EmpUnit in 'BackEnd\Employee\Domain\EmpUnit.pas',
  EmpUnit.Repository in 'BackEnd\Employee\Repository\EmpUnit.Repository.pas',
  EmpUnit.Service in 'BackEnd\Employee\Service\EmpUnit.Service.pas',
  ufrmEmpUnit in 'Forms\Employee\Input\ufrmEmpUnit.pas' {frmEmpUnit},
  ufrmEmpUnits in 'Forms\Employee\Output\ufrmEmpUnits.pas' {frmEmpUnits},
  EmpSection in 'BackEnd\Employee\Domain\EmpSection.pas',
  EmpSection.Repository in 'BackEnd\Employee\Repository\EmpSection.Repository.pas',
  EmpSection.Service in 'BackEnd\Employee\Service\EmpSection.Service.pas',
  ufrmEmpSection in 'Forms\Employee\Input\ufrmEmpSection.pas' {frmEmpSection},
  ufrmEmpSections in 'Forms\Employee\Output\ufrmEmpSections.pas' {frmEmpSections},
  EmpTask in 'BackEnd\Employee\Domain\EmpTask.pas',
  EmpTask.Repository in 'BackEnd\Employee\Repository\EmpTask.Repository.pas',
  EmpTask.Service in 'BackEnd\Employee\Service\EmpTask.Service.pas',
  ufrmEmpTask in 'Forms\Employee\Input\ufrmEmpTask.pas' {frmEmpTask},
  ufrmEmpTasks in 'Forms\Employee\Output\ufrmEmpTasks.pas' {frmEmpTasks},
  EmpLanguage in 'BackEnd\Employee\Domain\EmpLanguage.pas',
  EmpLanguage.Repository in 'BackEnd\Employee\Repository\EmpLanguage.Repository.pas',
  EmpLanguage.Service in 'BackEnd\Employee\Service\EmpLanguage.Service.pas',
  ufrmEmpLanguage in 'Forms\Employee\Input\ufrmEmpLanguage.pas' {frmEmpLanguage},
  ufrmEmpLanguages in 'Forms\Employee\Output\ufrmEmpLanguages.pas' {frmEmpLanguages},
  EmpLanguageLevel in 'BackEnd\Employee\Domain\EmpLanguageLevel.pas',
  EmpLanguageLevel.Repository in 'BackEnd\Employee\Repository\EmpLanguageLevel.Repository.pas',
  EmpLanguageLevel.Service in 'BackEnd\Employee\Service\EmpLanguageLevel.Service.pas',
  ufrmEmpLanguageLevel in 'Forms\Employee\Input\ufrmEmpLanguageLevel.pas' {frmEmpLanguageLevel},
  ufrmEmpLanguageLevels in 'Forms\Employee\Output\ufrmEmpLanguageLevels.pas' {frmEmpLanguageLevels},
  EmpDriverLicenceType in 'BackEnd\Employee\Domain\EmpDriverLicenceType.pas',
  EmpDriverLicenceType.Repository in 'BackEnd\Employee\Repository\EmpDriverLicenceType.Repository.pas',
  EmpDriverLicenceType.Service in 'BackEnd\Employee\Service\EmpDriverLicenceType.Service.pas',
  ufrmEmpDriverLicenceType in 'Forms\Employee\Input\ufrmEmpDriverLicenceType.pas' {frmEmpDriverLicenceType},
  ufrmEmpDriverLicenceTypes in 'Forms\Employee\Output\ufrmEmpDriverLicenceTypes.pas' {frmEmpDriverLicenceTypes},
  EmpDriverLicence in 'BackEnd\Employee\Domain\EmpDriverLicence.pas',
  EmpDriverLicence.Repository in 'BackEnd\Employee\Repository\EmpDriverLicence.Repository.pas',
  EmpDriverLicence.Service in 'BackEnd\Employee\Service\EmpDriverLicence.Service.pas',
  ufrmEmpDriverLicence in 'Forms\Employee\Input\ufrmEmpDriverLicence.pas' {frmEmpDriverLicence},
  ufrmEmpDriverLicences in 'Forms\Employee\Output\ufrmEmpDriverLicences.pas' {frmEmpDriverLicences},
  EmpLanguageAbility in 'BackEnd\Employee\Domain\EmpLanguageAbility.pas',
  EmpLanguageAbility.Repository in 'BackEnd\Employee\Repository\EmpLanguageAbility.Repository.pas',
  EmpLanguageAbility.Service in 'BackEnd\Employee\Service\EmpLanguageAbility.Service.pas',
  ufrmEmpLanguageAbility in 'Forms\Employee\Input\ufrmEmpLanguageAbility.pas' {frmEmpLanguageAbility},
  ufrmEmpLanguageAbilities in 'Forms\Employee\Output\ufrmEmpLanguageAbilities.pas' {frmEmpLanguageAbilities},
  EmpTransportation in 'BackEnd\Employee\Domain\EmpTransportation.pas',
  EmpTransportation.Repository in 'BackEnd\Employee\Repository\EmpTransportation.Repository.pas',
  EmpTransportation.Service in 'BackEnd\Employee\Service\EmpTransportation.Service.pas',
  ufrmEmpTransportation in 'Forms\Employee\Input\ufrmEmpTransportation.pas' {frmEmpTransportation},
  ufrmEmpTransportations in 'Forms\Employee\Output\ufrmEmpTransportations.pas' {frmEmpTransportations},
  EmpPersonAddress in 'BackEnd\Employee\Domain\EmpPersonAddress.pas',
  EmpPersonAddress.Repository in 'BackEnd\Employee\Repository\EmpPersonAddress.Repository.pas',
  EmpPersonAddress.Service in 'BackEnd\Employee\Service\EmpPersonAddress.Service.pas',
  ufrmEmpPersonAddress in 'Forms\Employee\Input\ufrmEmpPersonAddress.pas' {frmEmpPersonAddress},
  ufrmEmpPersonAddresses in 'Forms\Employee\Output\ufrmEmpPersonAddresses.pas' {frmEmpPersonAddresses},
  AccAccount in 'BackEnd\Account\Domain\AccAccount.pas',
  AccAccount.Repository in 'BackEnd\Account\Repository\AccAccount.Repository.pas',
  AccAccount.Service in 'BackEnd\Account\Service\AccAccount.Service.pas',
  ufrmAccAccount in 'Forms\Account\Input\ufrmAccAccount.pas' {frmAccAccount},
  ufrmAccAccountLookup in 'Forms\Account\Input\ufrmAccAccountLookup.pas' {frmAccAccountLookup},
  ufrmAccAccounts in 'Forms\Account\Output\ufrmAccAccounts.pas' {frmAccAccounts},
  ufrmAccAccountsLookup in 'Forms\Account\Output\ufrmAccAccountsLookup.pas' {frmAccAccountsLookup},
  AccAccountAddress in 'BackEnd\Account\Domain\AccAccountAddress.pas',
  AccAccountAddress.Repository in 'BackEnd\Account\Repository\AccAccountAddress.Repository.pas',
  AccAccountAddress.Service in 'BackEnd\Account\Service\AccAccountAddress.Service.pas',
  AccAccountPlan in 'BackEnd\Account\Domain\AccAccountPlan.pas',
  AccAccountPlan.Repository in 'BackEnd\Account\Repository\AccAccountPlan.Repository.pas',
  AccAccountPlan.Service in 'BackEnd\Account\Service\AccAccountPlan.Service.pas',
  ufrmAccAccountPlan in 'Forms\Account\Input\ufrmAccAccountPlan.pas' {frmAccAccountPlan},
  ufrmAccAccountPlans in 'Forms\Account\Output\ufrmAccAccountPlans.pas' {frmAccAccountPlans},
  AccBank in 'BackEnd\Account\Domain\AccBank.pas',
  AccBank.Repository in 'BackEnd\Account\Repository\AccBank.Repository.pas',
  AccBank.Service in 'BackEnd\Account\Service\AccBank.Service.pas',
  ufrmAccBank in 'Forms\Account\Input\ufrmAccBank.pas' {frmAccBank},
  ufrmAccBanks in 'Forms\Account\Output\ufrmAccBanks.pas' {frmAccBanks},
  AccBankBranch in 'BackEnd\Account\Domain\AccBankBranch.pas',
  AccBankBranch.Repository in 'BackEnd\Account\Repository\AccBankBranch.Repository.pas',
  AccBankBranch.Service in 'BackEnd\Account\Service\AccBankBranch.Service.pas',
  ufrmAccBankBranch in 'Forms\Account\Input\ufrmAccBankBranch.pas' {frmAccBankBranch},
  ufrmAccBankBranches in 'Forms\Account\Output\ufrmAccBankBranches.pas' {frmAccBankBranches},
  AccExchangeRate in 'BackEnd\Account\Domain\AccExchangeRate.pas',
  AccExchangeRate.Repository in 'BackEnd\Account\Repository\AccExchangeRate.Repository.pas',
  AccExchangeRate.Service in 'BackEnd\Account\Service\AccExchangeRate.Service.pas',
  ufrmAccExchangeRate in 'Forms\Account\Input\ufrmAccExchangeRate.pas' {frmAccExchangeRate},
  ufrmAccExchangeRates in 'Forms\Account\Output\ufrmAccExchangeRates.pas' {frmAccExchangeRates},
  AccGroup in 'BackEnd\Account\Domain\AccGroup.pas',
  AccGroup.Repository in 'BackEnd\Account\Repository\AccGroup.Repository.pas',
  AccGroup.Service in 'BackEnd\Account\Service\AccGroup.Service.pas',
  ufrmAccGroup in 'Forms\Account\Input\ufrmAccGroup.pas' {frmAccGroup},
  ufrmAccGroups in 'Forms\Account\Output\ufrmAccGroups.pas' {frmAccGroups},
  AccRegion in 'BackEnd\Account\Domain\AccRegion.pas',
  AccRegion.Repository in 'BackEnd\Account\Repository\AccRegion.Repository.pas',
  AccRegion.Service in 'BackEnd\Account\Service\AccRegion.Service.pas',
  ufrmAccRegion in 'Forms\Account\Input\ufrmAccRegion.pas' {frmAccRegion},
  ufrmAccRegions in 'Forms\Account\ufrmAccRegions.pas' {frmAccRegions},
  AccTransferCode in 'BackEnd\Account\Domain\AccTransferCode.pas',
  AccTransferCode.Repository in 'BackEnd\Account\Repository\AccTransferCode.Repository.pas',
  AccTransferCode.Service in 'BackEnd\Account\Service\AccTransferCode.Service.pas',
  AccVoucher in 'BackEnd\Account\Domain\AccVoucher.pas',
  AccVoucher.Repository in 'BackEnd\Account\Repository\AccVoucher.Repository.pas',
  AccVoucher.Service in 'BackEnd\Account\Service\AccVoucher.Service.pas',
  AccVoucherDetail in 'BackEnd\Account\Domain\AccVoucherDetail.pas',
  AccVoucherDetail.Repository in 'BackEnd\Account\Repository\AccVoucherDetail.Repository.pas',
  AccVoucherDetail.Service in 'BackEnd\Account\Service\AccVoucherDetail.Service.pas',
  SetAccAccountType in 'BackEnd\Account\Domain\SetAccAccountType.pas',
  SetAccAccountType.Repository in 'BackEnd\Account\Repository\SetAccAccountType.Repository.pas',
  SetAccAccountType.Service in 'BackEnd\Account\Service\SetAccAccountType.Service.pas',
  ufrmAccSetAccountType in 'Forms\Account\Input\ufrmAccSetAccountType.pas' {frmAccSetAccountType},
  ufrmAccSetAccountTypes in 'Forms\Account\ufrmAccSetAccountTypes.pas' {frmAccSetAccountTypes},
  SetAccCompanyLegalForm in 'BackEnd\Account\Domain\SetAccCompanyLegalForm.pas',
  SetAccCompanyLegalForm.Repository in 'BackEnd\Account\Repository\SetAccCompanyLegalForm.Repository.pas',
  SetAccCompanyLegalForm.Service in 'BackEnd\Account\Service\SetAccCompanyLegalForm.Service.pas',
  SetAccOwnershipType in 'BackEnd\Account\Domain\SetAccOwnershipType.pas',
  SetAccOwnershipType.Repository in 'BackEnd\Account\Repository\SetAccOwnershipType.Repository.pas',
  SetAccOwnershipType.Service in 'BackEnd\Account\Service\SetAccOwnershipType.Service.pas',
  SetAccTaxRate in 'BackEnd\Account\Domain\SetAccTaxRate.pas',
  SetAccTaxRate.Repository in 'BackEnd\Account\Repository\SetAccTaxRate.Repository.pas',
  SetAccTaxRate.Service in 'BackEnd\Account\Service\SetAccTaxRate.Service.pas',
  StkCardKindInfo in 'BackEnd\Stock\Domain\StkCardKindInfo.pas',
  StkCardKindInfo.Repository in 'BackEnd\Stock\Repository\StkCardKindInfo.Repository.pas',
  StkCardKindInfo.Service in 'BackEnd\Stock\Service\StkCardKindInfo.Service.pas',
  ufrmStkCardKindInfo in 'Forms\Stock\Input\ufrmStkCardKindInfo.pas' {frmStkCardKindInfo},
  ufrmStkCardKindInfos in 'Forms\Stock\Output\ufrmStkCardKindInfos.pas' {frmStkCardKindInfos},
  StkCardSummary in 'BackEnd\Stock\Domain\StkCardSummary.pas',
  StkCardSummary.Repository in 'BackEnd\Stock\Repository\StkCardSummary.Repository.pas',
  StkCardSummary.Service in 'BackEnd\Stock\Service\StkCardSummary.Service.pas',
  StkGroup in 'BackEnd\Stock\Domain\StkGroup.pas',
  StkGroup.Repository in 'BackEnd\Stock\Repository\StkGroup.Repository.pas',
  StkGroup.Service in 'BackEnd\Stock\Service\StkGroup.Service.pas',
  ufrmStkGroup in 'Forms\Stock\Input\ufrmStkGroup.pas' {frmStkGroup},
  ufrmStkGroups in 'Forms\Stock\Output\ufrmStkGroups.pas' {frmStkGroups},
  StkImage in 'BackEnd\Stock\Domain\StkImage.pas',
  StkImage.Repository in 'BackEnd\Stock\Repository\StkImage.Repository.pas',
  StkImage.Service in 'BackEnd\Stock\Service\StkImage.Service.pas',
  StkInventory in 'BackEnd\Stock\Domain\StkInventory.pas',
  StkInventory.Repository in 'BackEnd\Stock\Repository\StkInventory.Repository.pas',
  StkInventory.Service in 'BackEnd\Stock\Service\StkInventory.Service.pas',
  ufrmStkInventory in 'Forms\Stock\Input\ufrmStkInventory.pas' {frmStkInventory},
  ufrmStkInventories in 'Forms\Stock\Output\ufrmStkInventories.pas' {frmStkInventories},
  StkInventorySummary in 'BackEnd\Stock\Domain\StkInventorySummary.pas',
  StkInventorySummary.Repository in 'BackEnd\Stock\Repository\StkInventorySummary.Repository.pas',
  StkInventorySummary.Service in 'BackEnd\Stock\Service\StkInventorySummary.Service.pas',
  ufrmStkInventorySummary in 'Forms\Stock\Input\ufrmStkInventorySummary.pas' {frmStkInventorySummary},
  ufrmStkInventorySummaries in 'Forms\Stock\Output\ufrmStkInventorySummaries.pas' {frmStkInventorySummaries},
  StkKindFamily in 'BackEnd\Stock\Domain\StkKindFamily.pas',
  StkKindFamily.Repository in 'BackEnd\Stock\Repository\StkKindFamily.Repository.pas',
  StkKindFamily.Service in 'BackEnd\Stock\Service\StkKindFamily.Service.pas',
  ufrmStkKindFamily in 'Forms\Stock\Input\ufrmStkKindFamily.pas' {frmStkKindFamily},
  ufrmStkKindFamilies in 'Forms\Stock\Output\ufrmStkKindFamilies.pas' {frmStkKindFamilies},
  StkKindProperty in 'BackEnd\Stock\Domain\StkKindProperty.pas',
  StkKindProperty.Repository in 'BackEnd\Stock\Repository\StkKindProperty.Repository.pas',
  StkKindProperty.Service in 'BackEnd\Stock\Service\StkKindProperty.Service.pas',
  ufrmStkKindProperty in 'Forms\Stock\Input\ufrmStkKindProperty.pas' {frmStkKindProperty},
  ufrmStkKindProperties in 'Forms\Stock\Output\ufrmStkKindProperties.pas' {frmStkKindProperties},
  StkProductType in 'BackEnd\Stock\Domain\StkProductType.pas',
  StkProductType.Repository in 'BackEnd\Stock\Repository\StkProductType.Repository.pas',
  StkProductType.Service in 'BackEnd\Stock\Service\StkProductType.Service.pas',
  ufrmStkProductType in 'Forms\Stock\Input\ufrmStkProductType.pas' {frmStkProductType},
  ufrmStkProductTypes in 'Forms\Stock\Output\ufrmStkProductTypes.pas' {frmStkProductTypes},
  StkTransaction in 'BackEnd\Stock\Domain\StkTransaction.pas',
  StkTransaction.Repository in 'BackEnd\Stock\Repository\StkTransaction.Repository.pas',
  StkTransaction.Service in 'BackEnd\Stock\Service\StkTransaction.Service.pas',
  StkWarehouse in 'BackEnd\Stock\Domain\StkWarehouse.pas',
  StkWarehouse.Repository in 'BackEnd\Stock\Repository\StkWarehouse.Repository.pas',
  StkWarehouse.Service in 'BackEnd\Stock\Service\StkWarehouse.Service.pas',
  ufrmStkWarehouse in 'Forms\Stock\Input\ufrmStkWarehouse.pas' {frmStkWarehouse},
  ufrmStkWarehouses in 'Forms\Stock\Output\ufrmStkWarehouses.pas' {frmStkWarehouses},
  Core.Exception in 'BackEnd\Core\Core.Exception.pas',
  SysUser.Exception in 'BackEnd\System\Exception\SysUser.Exception.pas',
  SysLanguage.Exception in 'BackEnd\System\Exception\SysLanguage.Exception.pas',
  SysPermissionGroup.Exception in 'BackEnd\System\Exception\SysPermissionGroup.Exception.pas',
  SysPermission.Exception in 'BackEnd\System\Exception\SysPermission.Exception.pas',
  SysUomGroup.Exception in 'BackEnd\System\Exception\SysUomGroup.Exception.pas',
  SysUom.Exception in 'BackEnd\System\Exception\SysUom.Exception.pas',
  SysCity.Exception in 'BackEnd\System\Exception\SysCity.Exception.pas',
  SysCountry.Exception in 'BackEnd\System\Exception\SysCountry.Exception.pas',
  SysRegion.Exception in 'BackEnd\System\Exception\SysRegion.Exception.pas',
  SysCurrency.Exception in 'BackEnd\System\Exception\SysCurrency.Exception.pas',
  SysGridColumn.Exception in 'BackEnd\System\Exception\SysGridColumn.Exception.pas',
  SysGridFilter.Exception in 'BackEnd\System\Exception\SysGridFilter.Exception.pas',
  SysDecimalPlace.Exception in 'BackEnd\System\Exception\SysDecimalPlace.Exception.pas';

{$R *.res}

procedure MemLeakFix;
begin
  CheckSynchronize;
end;

begin
  Application.Initialize;
  Application.DefaultFont.Name := 'Tahoma';

  Application.UpdateFormatSettings := False;
  Formatsettings.ThousandSeparator := '.';
  Formatsettings.DecimalSeparator := ',';
  Formatsettings.DateSeparator := '.';
  Formatsettings.ShortDateFormat := 'dd.mm.yyyy';
  Formatsettings.LongDateFormat  := 'dd.mm.yyyy dddd';
  Formatsettings.ShortTimeFormat := 'HH:mm';
  Formatsettings.LongTimeFormat  := 'HH:mm:ss';
  Formatsettings.TimeSeparator   := ':';

{$WARN SYMBOL_PLATFORM OFF}
  {$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := {$IFDEF MSWINDOWS}DebugHook <> 0;{$ELSE}True;{$ENDIF MSWINDOWS}
  {$ENDIF}
{$WARN SYMBOL_PLATFORM ON}

  AddExitProc(MemLeakFix);

  TStyleManager.TrySetStyle('Iceberg Classico');
  Application.Title := 'THS ERP';
  Application.CreateForm(Tdm, dm);
  Application.CreateForm(TfrmDashboard, frmDashboard);
  if TfrmLogin.Execute then
  begin
    Application.ShowMainForm := True;
    Application.Run;
  end
  else
  begin
    Application.Terminate;
  end;
end.
