program ThsERP;

{$I ThsERP.inc}

uses
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  System.StartUpCopy,
  System.Classes,
  System.SysUtils,
  Winapi.Messages,
  Winapi.Windows,
  System.IOUtils,
  udm in 'BackEnd\Framework\udm.pas' {dm: TDataModule},
  Ths.Erp.Helper.BaseTypes in 'BackEnd\Tools\Ths.Erp.Helper.BaseTypes.pas',
  Ths.Erp.Helper.Button in 'BackEnd\Tools\Ths.Erp.Helper.Button.pas',
  Ths.Erp.Helper.ComboBox in 'BackEnd\Tools\Ths.Erp.Helper.ComboBox.pas',
  Ths.Erp.Helper.CustomFileDialog in 'BackEnd\Tools\Ths.Erp.Helper.CustomFileDialog.pas',
  Ths.Erp.Helper.Edit in 'BackEnd\Tools\Ths.Erp.Helper.Edit.pas',
  Ths.Erp.Helper.Memo in 'BackEnd\Tools\Ths.Erp.Helper.Memo.pas',
  Ths.Erp.Helper.SpinEdit in 'BackEnd\Tools\Ths.Erp.Helper.SpinEdit.pas',
  Ths.Erp.Helper.StringGrid in 'BackEnd\Tools\Ths.Erp.Helper.StringGrid.pas',
  Ths.Erp.Utils.SevenZip in 'BackEnd\Tools\Ths.Erp.Utils.SevenZip.pas',
  Ths.Erp.Utils.FluentXML in 'BackEnd\Tools\Ths.Erp.Utils.FluentXML.pas',
  Ths.Erp.Utils.InfoWindow in 'BackEnd\Tools\Ths.Erp.Utils.InfoWindow.pas',
  Ths.Erp.Globals in 'BackEnd\Framework\Ths.Erp.Globals.pas',
  Ths.Erp.Constants in 'BackEnd\Framework\Ths.Erp.Constants.pas',
  Ths.Erp.Database.Connection.Settings in 'BackEnd\Framework\Ths.Erp.Database.Connection.Settings.pas',
  Ths.Erp.Database in 'BackEnd\Framework\Ths.Erp.Database.pas',
  Ths.Erp.Database.Singleton in 'BackEnd\Framework\Ths.Erp.Database.Singleton.pas',
  Ths.Erp.Database.Table in 'BackEnd\Framework\Ths.Erp.Database.Table.pas',
  Ths.Erp.Database.TableDetailed in 'BackEnd\Framework\Ths.Erp.Database.TableDetailed.pas',
  NetGsm_SMS in 'BackEnd\Tools\NetGsm_SMS.pas',
  ufrmAbout in 'Forms\ufrmAbout.pas' {frmAbout},
  ufrmBase in 'Forms\ufrmBase.pas' {frmBase},
  ufrmBaseInput in 'Forms\ufrmBaseInput.pas' {frmBaseInput},
  ufrmConfirmation in 'Forms\ufrmConfirmation.pas' {frmConfirmation},
  ufrmBaseDetaylar in 'Forms\DetailedInputForms\Factory\ufrmBaseDetaylar.pas' {frmBaseDetaylar},
  ufrmBaseDetaylarDetay in 'Forms\DetailedInputForms\Factory\ufrmBaseDetaylarDetay.pas' {frmBaseDetaylarDetay},
  ufrmBaseInputDB in 'Forms\InputForms\Factory\ufrmBaseInputDB.pas' {frmBaseInputDB},
  ufrmBaseOutput in 'Forms\OutputForms\Factory\ufrmBaseOutput.pas' {frmBaseOutput},
  ufrmBaseDBGrid in 'Forms\OutputForms\DbGrid\Factory\ufrmBaseDBGrid.pas' {frmBaseDBGrid},
  ufrmFilterDBGrid in 'Forms\OutputForms\DbGrid\Factory\ufrmFilterDBGrid.pas' {frmFilterDBGrid},
  ufrmBaseStrGrid in 'Forms\OutputForms\StrGrid\Factory\ufrmBaseStrGrid.pas' {frmBaseStrGrid},
  ufrmLogin in 'Forms\InputForms\Framework\ufrmLogin.pas' {frmLogin},
  ufrmMain in 'Forms\InputForms\Framework\ufrmMain.pas' {frmMain},
  ufrmCalculator in 'Forms\ufrmCalculator.pas' {frmCalculator},
  Ths.Erp.Database.Table.SysAdres in 'BackEnd\Framework\Ths.Erp.Database.Table.SysAdres.pas',
  Ths.Erp.Database.Table.SysUygulamaAyari in 'BackEnd\Framework\Ths.Erp.Database.Table.SysUygulamaAyari.pas',
  ufrmSysUygulamaAyari in 'Forms\InputForms\Framework\ufrmSysUygulamaAyari.pas' {frmSysUygulamaAyari},
  Ths.Erp.Database.Table.SysUygulamaAyariDiger in 'BackEnd\Framework\Ths.Erp.Database.Table.SysUygulamaAyariDiger.pas',
  ufrmSysUygulamaAyariDiger in 'Forms\InputForms\Framework\ufrmSysUygulamaAyariDiger.pas' {frmSysUygulamaAyariDiger},
  Ths.Erp.Database.Table.SysMahalle in 'BackEnd\Framework\Ths.Erp.Database.Table.SysMahalle.pas',
  ufrmSysMahalleler in 'Forms\OutputForms\DbGrid\Framework\ufrmSysMahalleler.pas' {frmSysMahalleler},
  ufrmSysMahalle in 'Forms\InputForms\Framework\ufrmSysMahalle.pas' {frmSysMahalle},
  Ths.Erp.Database.Table.SysSemt in 'BackEnd\Framework\Ths.Erp.Database.Table.SysSemt.pas',
  ufrmSysSemtler in 'Forms\OutputForms\DbGrid\Framework\ufrmSysSemtler.pas' {frmSysSemtler},
  ufrmSysSemt in 'Forms\InputForms\Framework\ufrmSysSemt.pas' {frmSysSemt},
  Ths.Erp.Database.Table.SysIlce in 'BackEnd\Framework\Ths.Erp.Database.Table.SysIlce.pas',
  ufrmSysIlceler in 'Forms\OutputForms\DbGrid\Framework\ufrmSysIlceler.pas' {frmSysIlceler},
  ufrmSysIlce in 'Forms\InputForms\Framework\ufrmSysIlce.pas' {frmSysIlce},
  Ths.Erp.Database.Table.SysSehir in 'BackEnd\Framework\Ths.Erp.Database.Table.SysSehir.pas',
  ufrmSysSehirler in 'Forms\OutputForms\DbGrid\Framework\ufrmSysSehirler.pas' {frmSysSehirler},
  ufrmSysSehir in 'Forms\InputForms\Framework\ufrmSysSehir.pas' {frmSysSehir},
  Ths.Erp.Database.Table.SysBolge in 'BackEnd\Framework\Ths.Erp.Database.Table.SysBolge.pas',
  ufrmSysBolgeler in 'Forms\OutputForms\DbGrid\Framework\ufrmSysBolgeler.pas' {frmSysBolgeler},
  ufrmSysBolge in 'Forms\InputForms\Framework\ufrmSysBolge.pas' {frmSysBolge},
  Ths.Erp.Database.Table.SysUlke in 'BackEnd\Framework\Ths.Erp.Database.Table.SysUlke.pas',
  ufrmSysUlkeler in 'Forms\OutputForms\DbGrid\Framework\ufrmSysUlkeler.pas' {frmSysUlkeler},
  ufrmSysUlke in 'Forms\InputForms\Framework\ufrmSysUlke.pas' {frmSysUlke},
  Ths.Erp.Database.Table.SysGun in 'BackEnd\Framework\Ths.Erp.Database.Table.SysGun.pas',
  ufrmSysGunler in 'Forms\OutputForms\DbGrid\Framework\ufrmSysGunler.pas' {frmSysGunler},
  ufrmSysGun in 'Forms\InputForms\Framework\ufrmSysGun.pas' {frmSysGun},
  Ths.Erp.Database.Table.SysOndalikHane in 'BackEnd\Framework\Ths.Erp.Database.Table.SysOndalikHane.pas',
  Ths.Erp.Database.Table.SysGridKolon in 'BackEnd\Framework\Ths.Erp.Database.Table.SysGridKolon.pas',
  ufrmSysGridKolonlar in 'Forms\OutputForms\DbGrid\Framework\ufrmSysGridKolonlar.pas' {frmSysGridKolonlar},
  ufrmSysGridKolon in 'Forms\InputForms\Framework\ufrmSysGridKolon.pas' {frmSysGridKolon},
  Ths.Erp.Database.Table.SysGridFiltreSiralama in 'BackEnd\Framework\Ths.Erp.Database.Table.SysGridFiltreSiralama.pas',
  ufrmSysGridFiltreSiralamalar in 'Forms\OutputForms\DbGrid\Framework\ufrmSysGridFiltreSiralamalar.pas' {frmSysGridFiltreSiralamalar},
  ufrmSysGridFiltreSiralama in 'Forms\InputForms\Framework\ufrmSysGridFiltreSiralama.pas' {frmSysGridFiltreSiralama},
  Ths.Erp.Database.Table.SysLisan in 'BackEnd\Framework\Ths.Erp.Database.Table.SysLisan.pas',
  ufrmSysLisanlar in 'Forms\OutputForms\DbGrid\Framework\ufrmSysLisanlar.pas' {frmSysLisanlar},
  ufrmSysLisan in 'Forms\InputForms\Framework\ufrmSysLisan.pas' {frmSysLisan},
  Ths.Erp.Database.Table.SysLisanDataIcerik in 'BackEnd\Framework\Ths.Erp.Database.Table.SysLisanDataIcerik.pas',
  ufrmSysLisanDataIcerikler in 'Forms\OutputForms\DbGrid\Framework\ufrmSysLisanDataIcerikler.pas' {frmSysLisanDataIcerikler},
  ufrmSysLisanDataIcerik in 'Forms\InputForms\Framework\ufrmSysLisanDataIcerik.pas' {frmSysLangDataContent},
  Ths.Erp.Database.Table.SysLisanGuiIcerik in 'BackEnd\Framework\Ths.Erp.Database.Table.SysLisanGuiIcerik.pas',
  ufrmSysLisanGuiIcerikler in 'Forms\OutputForms\DbGrid\Framework\ufrmSysLisanGuiIcerikler.pas' {frmSysLisanGuiIcerikler},
  ufrmSysLisanGuiIcerik in 'Forms\InputForms\Framework\ufrmSysLisanGuiIcerik.pas' {frmSysLisanGuiIcerik},
  Ths.Erp.Database.Table.SysAy in 'BackEnd\Framework\Ths.Erp.Database.Table.SysAy.pas',
  ufrmSysAylar in 'Forms\OutputForms\DbGrid\Framework\ufrmSysAylar.pas' {frmSysAylar},
  ufrmSysAy in 'Forms\InputForms\Framework\ufrmSysAy.pas' {frmSysAy},
  Ths.Erp.Database.Table.SysKaynak in 'BackEnd\Framework\Ths.Erp.Database.Table.SysKaynak.pas',
  ufrmSysKaynaklar in 'Forms\OutputForms\DbGrid\Framework\ufrmSysKaynaklar.pas' {frmSysKaynaklar},
  ufrmSysKaynak in 'Forms\InputForms\Framework\ufrmSysKaynak.pas' {frmSysKaynak},
  Ths.Erp.Database.Table.SysKaynakGrup in 'BackEnd\Framework\Ths.Erp.Database.Table.SysKaynakGrup.pas',
  ufrmSysKaynakGruplari in 'Forms\OutputForms\DbGrid\Framework\ufrmSysKaynakGruplari.pas' {frmSysKaynakGruplari},
  ufrmSysKaynakGrubu in 'Forms\InputForms\Framework\ufrmSysKaynakGrubu.pas' {frmSysKaynakGrubu},
  Ths.Erp.Database.Table.SysKaliteFormNo in 'BackEnd\Framework\Ths.Erp.Database.Table.SysKaliteFormNo.pas',
  ufrmSysKaliteFormNolar in 'Forms\OutputForms\DbGrid\Framework\ufrmSysKaliteFormNolar.pas' {frmSysKaliteFormNolar},
  ufrmSysKaliteFormNo in 'Forms\InputForms\Framework\ufrmSysKaliteFormNo.pas' {frmSysKaliteFormNo},
  Ths.Erp.Database.Table.SysKaliteFormTipi in 'BackEnd\Framework\Ths.Erp.Database.Table.SysKaliteFormTipi.pas',
  ufrmSysKaliteFormTipleri in 'Forms\OutputForms\DbGrid\Framework\ufrmSysKaliteFormTipleri.pas' {frmSysKaliteFormTipleri},
  ufrmSysKaliteFormTipi in 'Forms\InputForms\Framework\ufrmSysKaliteFormTipi.pas' {frmSysKaliteFormTipi},
  Ths.Erp.Database.Table.SysMukellefTipi in 'BackEnd\Framework\Ths.Erp.Database.Table.SysMukellefTipi.pas',
  ufrmSysMukellefTipleri in 'Forms\OutputForms\DbGrid\Framework\ufrmSysMukellefTipleri.pas' {frmSysMukellefTipleri},
  ufrmSysMukellefTipi in 'Forms\InputForms\Framework\ufrmSysMukellefTipi.pas' {frmSysMukellefTipi},
  Ths.Erp.Database.Table.SysParaBirimi in 'BackEnd\Framework\Ths.Erp.Database.Table.SysParaBirimi.pas',
  ufrmSysParaBirimleri in 'Forms\OutputForms\DbGrid\Framework\ufrmSysParaBirimleri.pas' {frmSysParaBirimleri},
  ufrmSysParaBirimi in 'Forms\InputForms\Framework\ufrmSysParaBirimi.pas' {frmSysParaBirimi},
  Ths.Erp.Database.Table.SysOlcuBirimiTipi in 'BackEnd\Framework\Ths.Erp.Database.Table.SysOlcuBirimiTipi.pas',
  ufrmSysOlcuBirimiTipleri in 'Forms\OutputForms\DbGrid\Framework\ufrmSysOlcuBirimiTipleri.pas' {frmSysOlcuBirimiTipleri},
  ufrmSysOlcuBirimiTipi in 'Forms\InputForms\Framework\ufrmSysOlcuBirimiTipi.pas' {frmSysOlcuBirimiTipi},
  Ths.Erp.Database.Table.SysOlcuBirimi in 'BackEnd\Framework\Ths.Erp.Database.Table.SysOlcuBirimi.pas',
  ufrmSysOlcuBirimleri in 'Forms\OutputForms\DbGrid\Framework\ufrmSysOlcuBirimleri.pas' {frmSysOlcuBirimleri},
  ufrmSysOlcuBirimi in 'Forms\InputForms\Framework\ufrmSysOlcuBirimi.pas' {frmSysOlcuBirimi},
  Ths.Erp.Database.Table.SysKullanici in 'BackEnd\Framework\Ths.Erp.Database.Table.SysKullanici.pas',
  ufrmSysKullanicilar in 'Forms\OutputForms\DbGrid\Framework\ufrmSysKullanicilar.pas' {frmSysKullanicilar},
  ufrmSysKullanici in 'Forms\InputForms\Framework\ufrmSysKullanici.pas' {frmSysKullanici},
  Ths.Erp.Database.Table.SysErisimHakki in 'BackEnd\Framework\Ths.Erp.Database.Table.SysErisimHakki.pas',
  ufrmSysErisimHaklari in 'Forms\OutputForms\DbGrid\Framework\ufrmSysErisimHaklari.pas' {frmSysUserAccessRights},
  ufrmSysErisimHakki in 'Forms\InputForms\Framework\ufrmSysErisimHakki.pas' {frmSysUserAccessRight},
  Ths.Erp.Database.Table.View in 'BackEnd\Framework\Ths.Erp.Database.Table.View.pas',
  Ths.Erp.Database.Table.View.SysViewColumns in 'BackEnd\Framework\Ths.Erp.Database.Table.View.SysViewColumns.pas',
  Ths.Erp.Database.Table.View.SysDbStatus in 'BackEnd\Framework\Ths.Erp.Database.Table.View.SysDbStatus.pas',
  Ths.Erp.Database.Table.View.SysViewTables in 'BackEnd\Framework\Ths.Erp.Database.Table.View.SysViewTables.pas',
  ufrmSysTables in 'Forms\OutputForms\DbGrid\Framework\ufrmSysTables.pas' {frmSysTables},
  ufrmSysSifreGuncelle in 'Forms\InputForms\Framework\ufrmSysSifreGuncelle.pas' {frmSysSifreGuncelle},
  ufrmSysDbStatus in 'Forms\OutputForms\DbGrid\Framework\ufrmSysDbStatus.pas' {frmSysDbStatus},
  Ths.Erp.Database.Table.SetEinvFaturaTipi in 'BackEnd\Erp\Einv\Ths.Erp.Database.Table.SetEinvFaturaTipi.pas',
  ufrmSetEinvFaturaTipleri in 'Forms\OutputForms\DbGrid\Erp\Einv\ufrmSetEinvFaturaTipleri.pas' {frmSetEinvFaturaTipleri},
  ufrmSetEinvFaturaTipi in 'Forms\InputForms\Erp\Einv\ufrmSetEinvFaturaTipi.pas' {frmSetEinvFaturaTipi},
  Ths.Erp.Database.Table.SetEinvIstisnaKodu in 'BackEnd\Erp\Einv\Ths.Erp.Database.Table.SetEinvIstisnaKodu.pas',
  ufrmSetEinvIstisnaKodlari in 'Forms\OutputForms\DbGrid\Erp\Einv\ufrmSetEinvIstisnaKodlari.pas' {frmSetEinvIstisnaKodlari},
  ufrmSetEinvIstisnaKodu in 'Forms\InputForms\Erp\Einv\ufrmSetEinvIstisnaKodu.pas' {frmSetEinvIstisnaKodu},
  Ths.Erp.Database.Table.SetEinvTasimaUcreti in 'BackEnd\Erp\Einv\Ths.Erp.Database.Table.SetEinvTasimaUcreti.pas',
  ufrmSetEinvTasimaUcretleri in 'Forms\OutputForms\DbGrid\Erp\Einv\ufrmSetEinvTasimaUcretleri.pas' {frmSetEinvNakliyeUcretleri},
  ufrmSetEinvTasimaUcreti in 'Forms\InputForms\Erp\Einv\ufrmSetEinvTasimaUcreti.pas' {frmSetEinvTasimaUcreti},
  Ths.Erp.Database.Table.SetEinvTeslimSekli in 'BackEnd\Erp\Einv\Ths.Erp.Database.Table.SetEinvTeslimSekli.pas',
  ufrmSetEinvTeslimSekilleri in 'Forms\OutputForms\DbGrid\Erp\Einv\ufrmSetEinvTeslimSekilleri.pas' {frmSetEinvTeslimSekilleri},
  ufrmSetEinvTeslimSekli in 'Forms\InputForms\Erp\Einv\ufrmSetEinvTeslimSekli.pas' {frmSetEinvTeslimSekli},
  Ths.Erp.Database.Table.SetEinvOdemeSekli in 'BackEnd\Erp\Einv\Ths.Erp.Database.Table.SetEinvOdemeSekli.pas',
  ufrmSetEinvOdemeSekilleri in 'Forms\OutputForms\DbGrid\Erp\Einv\ufrmSetEinvOdemeSekilleri.pas' {frmSetEinvOdemeSekilleri},
  ufrmSetEinvOdemeSekli in 'Forms\InputForms\Erp\Einv\ufrmSetEinvOdemeSekli.pas' {frmSetEinvOdemeSekli},
  Ths.Erp.Database.Table.SetEinvPaketTipi in 'BackEnd\Erp\Einv\Ths.Erp.Database.Table.SetEinvPaketTipi.pas',
  ufrmSetEinvPaketTipleri in 'Forms\OutputForms\DbGrid\Erp\Einv\ufrmSetEinvPaketTipleri.pas' {frmSetEinvPaketTipleri},
  ufrmSetEinvPaketTipi in 'Forms\InputForms\Erp\Einv\ufrmSetEinvPaketTipi.pas' {frmSetEinvPaketTipi},
  Ths.Erp.Database.Table.MhsDovizKuru in 'BackEnd\Erp\Mhs\Ths.Erp.Database.Table.MhsDovizKuru.pas',
  ufrmMhsDovizKurlari in 'Forms\OutputForms\DbGrid\Erp\Mhs\ufrmMhsDovizKurlari.pas' {frmMhsDovizKurlari},
  ufrmMhsDovizKuru in 'Forms\InputForms\Erp\Mhs\ufrmMhsDovizKuru.pas' {frmMhsDovizKuru},
  Ths.Erp.Database.Table.RctIscilikGideri in 'BackEnd\Erp\Urt\Ths.Erp.Database.Table.RctIscilikGideri.pas',
  ufrmRctIscilikGiderleri in 'Forms\OutputForms\DbGrid\Erp\Urt\ufrmRctIscilikGiderleri.pas' {frmRctIscilikGiderleri},
  ufrmRctIscilikGideri in 'Forms\InputForms\Erp\Urt\ufrmRctIscilikGideri.pas' {frmRctIscilikGideri},
  Ths.Erp.Database.Table.SetRctIscilikGiderTipi in 'BackEnd\Erp\Urt\Ths.Erp.Database.Table.SetRctIscilikGiderTipi.pas',
  ufrmSetRctIscilikGiderTipleri in 'Forms\OutputForms\DbGrid\Erp\Urt\ufrmSetRctIscilikGiderTipleri.pas' {frmSetRctIscilikGiderTipleri},
  ufrmSetRctIscilikGiderTipi in 'Forms\InputForms\Erp\Urt\ufrmSetRctIscilikGiderTipi.pas' {frmSetRctIscilikGiderTipi},
  Ths.Erp.Database.Table.RctRecete in 'BackEnd\Erp\Urt\Ths.Erp.Database.Table.RctRecete.pas',
  ufrmRctReceteler in 'Forms\OutputForms\DbGrid\Erp\Urt\ufrmRctReceteler.pas' {frmRctReceteler},
  ufrmRctReceteDetaylar in 'Forms\DetailedInputForms\Erp\Urt\ufrmRctReceteDetaylar.pas' {frmRctReceteDetaylar},
  ufrmRctReceteHammadde in 'Forms\DetailedInputForms\Erp\Urt\ufrmRctReceteHammadde.pas' {frmRctReceteHammadde},
  ufrmRctReceteIscilik in 'Forms\DetailedInputForms\Erp\Urt\ufrmRctReceteIscilik.pas' {frmRctReceteIscilik},
  ufrmRctReceteYanUrun in 'Forms\DetailedInputForms\Erp\Urt\ufrmRctReceteYanUrun.pas' {frmRctReceteYanUrun},
  Ths.Erp.Database.Table.RctPaketHammadde in 'BackEnd\Erp\Urt\Ths.Erp.Database.Table.RctPaketHammadde.pas',
  ufrmRctPaketHammaddeler in 'Forms\OutputForms\DbGrid\Erp\Urt\ufrmRctPaketHammaddeler.pas' {frmRctPaketHammaddeler},
  ufrmRctPaketHammaddeDetaylar in 'Forms\DetailedInputForms\Erp\Urt\ufrmRctPaketHammaddeDetaylar.pas' {frmRctPaketHammaddeDetaylar},
  ufrmRctPaketHammaddeDetay in 'Forms\DetailedInputForms\Erp\Urt\ufrmRctPaketHammaddeDetay.pas' {frmRctPaketHammaddeDetay},
  Ths.Erp.Database.Table.SetChFirmaTipi in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.SetChFirmaTipi.pas',
  ufrmSetChFirmaTipleri in 'Forms\OutputForms\DbGrid\Erp\Ch\ufrmSetChFirmaTipleri.pas' {frmSetChFirmaTipleri},
  ufrmSetChFirmaTipi in 'Forms\InputForms\Erp\Ch\ufrmSetChFirmaTipi.pas' {frmSetChFirmaTipi},
  Ths.Erp.Database.Table.SetChFirmaTuru in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.SetChFirmaTuru.pas',
  ufrmSetChFirmaTurleri in 'Forms\OutputForms\DbGrid\Erp\Ch\ufrmSetChFirmaTurleri.pas' {frmSetChFirmaTurleri},
  ufrmSetChFirmaTuru in 'Forms\InputForms\Erp\Ch\ufrmSetChFirmaTuru.pas' {frmSetChFirmaTuru},
  Ths.Erp.Database.Table.SetChGrup in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.SetChGrup.pas',
  ufrmSetChGruplar in 'Forms\OutputForms\DbGrid\Erp\Ch\ufrmSetChGruplar.pas' {frmSetChGruplar},
  ufrmSetChGrup in 'Forms\InputForms\Erp\Ch\ufrmSetChGrup.pas' {frmSetChGrup},
  Ths.Erp.Database.Table.SetChHesapPlani in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.SetChHesapPlani.pas',
  ufrmSetChHesapPlanlari in 'Forms\OutputForms\DbGrid\Erp\Ch\ufrmSetChHesapPlanlari.pas' {frmSetChHesapPlanlari},
  ufrmSetChHesapPlani in 'Forms\InputForms\Erp\Ch\ufrmSetChHesapPlani.pas' {frmSetChHesapPlani},
  Ths.Erp.Database.Table.SetChHesapTipi in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.SetChHesapTipi.pas',
  ufrmSetChHesapTipleri in 'Forms\OutputForms\DbGrid\Erp\Ch\ufrmSetChHesapTipleri.pas' {frmSetChHesapTipleri},
  ufrmSetChHesapTipi in 'Forms\InputForms\Erp\Ch\ufrmSetChHesapTipi.pas' {frmSetChHesapTipi},
  Ths.Erp.Database.Table.SetChVergiOrani in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.SetChVergiOrani.pas',
  ufrmSetChVergiOranlari in 'Forms\OutputForms\DbGrid\Erp\Ch\ufrmSetChVergiOranlari.pas' {frmSetChVergiOranlari},
  ufrmSetChVergiOrani in 'Forms\InputForms\Erp\Ch\ufrmSetChVergiOrani.pas' {frmSetChVergiOrani},
  Ths.Erp.Database.Table.ChBanka in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.ChBanka.pas',
  ufrmChBankalar in 'Forms\OutputForms\DbGrid\Erp\Ch\ufrmChBankalar.pas' {frmChBankalar},
  ufrmChBanka in 'Forms\InputForms\Erp\Ch\ufrmChBanka.pas' {frmChBanka},
  Ths.Erp.Database.Table.ChBankaSubesi in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.ChBankaSubesi.pas',
  ufrmChBankaSubeleri in 'Forms\OutputForms\DbGrid\Erp\Ch\ufrmChBankaSubeleri.pas' {frmChBankaSubeleri},
  ufrmChBankaSubesi in 'Forms\InputForms\Erp\Ch\ufrmChBankaSubesi.pas' {frmChBankaSubesi},
  Ths.Erp.Database.Table.ChBolge in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.ChBolge.pas',
  ufrmChBolgeler in 'Forms\OutputForms\DbGrid\Erp\Ch\ufrmChBolgeler.pas' {frmChBolgeler},
  ufrmChBolge in 'Forms\InputForms\Erp\Ch\ufrmChBolge.pas' {frmChBolge},
  Ths.Erp.Database.Table.ChHesapKarti in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.ChHesapKarti.pas',
  ufrmChHesapKartlari in 'Forms\OutputForms\DbGrid\Erp\Ch\ufrmChHesapKartlari.pas' {frmHesapKartlari},
  ufrmChHesapKarti in 'Forms\InputForms\Erp\Ch\ufrmChHesapKarti.pas' {frmHesapKarti},
  Ths.Erp.Database.Table.ChHesapKartiAra in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.ChHesapKartiAra.pas',
  ufrmChHesapKartlariAra in 'Forms\OutputForms\DbGrid\Erp\Ch\ufrmChHesapKartlariAra.pas' {frmHesapKartlariAra},
  ufrmChHesapKartiAra in 'Forms\InputForms\Erp\Ch\ufrmChHesapKartiAra.pas' {frmHesapKartiAra},
  Ths.Erp.Database.Table.SetStkUrunTipi in 'BackEnd\Erp\Stk\Ths.Erp.Database.Table.SetStkUrunTipi.pas',
  ufrmSetStkUrunTipleri in 'Forms\OutputForms\DbGrid\Erp\Stk\ufrmSetStkUrunTipleri.pas' {frmSetStkUrunTipleri},
  ufrmSetStkUrunTipi in 'Forms\InputForms\Erp\Stk\ufrmSetStkUrunTipi.pas' {frmSetStkUrunTipi},
  Ths.Erp.Database.Table.StkCinsOzelligi in 'BackEnd\Erp\Stk\Ths.Erp.Database.Table.StkCinsOzelligi.pas',
  ufrmStkCinsOzellikleri in 'Forms\OutputForms\DbGrid\Erp\Stk\ufrmStkCinsOzellikleri.pas' {frmStkCinsOzellikleri},
  ufrmStkCinsOzelligi in 'Forms\InputForms\Erp\Stk\ufrmStkCinsOzelligi.pas' {frmStkCinsOzelligi},
  Ths.Erp.Database.Table.StkStokGrubu in 'BackEnd\Erp\Stk\Ths.Erp.Database.Table.StkStokGrubu.pas',
  ufrmStkStokGruplari in 'Forms\OutputForms\DbGrid\Erp\Stk\ufrmStkStokGruplari.pas' {frmStkStokGruplari},
  ufrmStkStokGrubu in 'Forms\InputForms\Erp\Stk\ufrmStkStokGrubu.pas' {frmStkStokGrubu},
  Ths.Erp.Database.Table.StkStokAmbar in 'BackEnd\Erp\Stk\Ths.Erp.Database.Table.StkStokAmbar.pas',
  ufrmStkStokAmbarlar in 'Forms\OutputForms\DbGrid\Erp\Stk\ufrmStkStokAmbarlar.pas' {frmStkStokAmbarlar},
  ufrmStkStokAmbar in 'Forms\InputForms\Erp\Stk\ufrmStkStokAmbar.pas' {frmStkStokAmbar},
  Ths.Erp.Database.Table.StkStokKarti in 'BackEnd\Erp\Stk\Ths.Erp.Database.Table.StkStokKarti.pas',
  ufrmStkStokKartlari in 'Forms\OutputForms\DbGrid\Erp\Stk\ufrmStkStokKartlari.pas' {frmStkStokKartlari},
  ufrmStkStokKarti in 'Forms\InputForms\Erp\Stk\ufrmStkStokKarti.pas' {frmStkStokKarti},
  Ths.Erp.Database.Table.StkStokHareketi in 'BackEnd\Erp\Stk\Ths.Erp.Database.Table.StkStokHareketi.pas',
  ufrmStkStokHareketleri in 'Forms\OutputForms\DbGrid\Erp\Stk\ufrmStkStokHareketleri.pas' {frmStkStokHareketleri},
  Ths.Erp.Database.Table.OthMailReciever in 'BackEnd\Erp\Oth\Ths.Erp.Database.Table.OthMailReciever.pas',
  ufrmOthMailRecievers in 'Forms\OutputForms\DbGrid\Erp\Oth\ufrmOthMailRecievers.pas' {frmOthMailRecievers},
  ufrmOthMailReciever in 'Forms\InputForms\Erp\Oth\ufrmOthMailReciever.pas' {frmOthMailReciever},
  Ths.Erp.Database.Table.SetSatTeklifDurum in 'BackEnd\Erp\Tek\Ths.Erp.Database.Table.SetSatTeklifDurum.pas',
  ufrmSetSatTeklifDurumlar in 'Forms\OutputForms\DbGrid\Erp\Tek\ufrmSetSatTeklifDurumlar.pas' {frmSetSatTeklifDurumlar},
  ufrmSetSatTeklifDurum in 'Forms\InputForms\Erp\Tek\ufrmSetSatTeklifDurum.pas' {frmSetSatTeklifDurum},
  Ths.Erp.Database.Table.SetTekTeklifTipi in 'BackEnd\Erp\Tek\Ths.Erp.Database.Table.SetTekTeklifTipi.pas',
  ufrmSetTekTeklifTipleri in 'Forms\OutputForms\DbGrid\Erp\Tek\ufrmSetTekTeklifTipleri.pas' {frmSetTekTeklifTipleri},
  ufrmSetTekTeklifTipi in 'Forms\InputForms\Erp\Tek\ufrmSetTekTeklifTipi.pas' {frmSetTekTeklifTipi},
  Ths.Erp.Database.Table.SatTeklif in 'BackEnd\Erp\Tek\Ths.Erp.Database.Table.SatTeklif.pas',
  ufrmSatTeklifler in 'Forms\OutputForms\DbGrid\Erp\Tek\ufrmSatTeklifler.pas' {frmSatTeklifler},
  ufrmSatTeklifDetay in 'Forms\DetailedInputForms\Erp\Tek\ufrmSatTeklifDetay.pas' {frmSatTeklifDetay},
  ufrmSatTeklifDetaylar in 'Forms\DetailedInputForms\Erp\Tek\ufrmSatTeklifDetaylar.pas' {frmSatTeklifDetaylar},
  Ths.Erp.Database.Table.SetSatSiparisDurum in 'BackEnd\Erp\Sip\Ths.Erp.Database.Table.SetSatSiparisDurum.pas',
  ufrmSetSatSiparisDurumlar in 'Forms\OutputForms\DbGrid\Erp\Sip\ufrmSetSatSiparisDurumlar.pas' {frmSetSatSiparisDurumlar},
  ufrmSetSatSiparisDurum in 'Forms\InputForms\Erp\Sip\ufrmSetSatSiparisDurum.pas' {frmSetSatSiparisDurum},
  Ths.Erp.Database.Table.SatSiparis in 'BackEnd\Erp\Sip\Ths.Erp.Database.Table.SatSiparis.pas',
  ufrmSatSiparisler in 'Forms\OutputForms\DbGrid\Erp\Sip\ufrmSatSiparisler.pas' {frmSatSiparisler},
  ufrmSatSiparisDetaylar in 'Forms\DetailedInputForms\Erp\Sip\ufrmSatSiparisDetaylar.pas' {frmSatSiparisDetaylar},
  ufrmSatSiparisDetay in 'Forms\DetailedInputForms\Erp\Sip\ufrmSatSiparisDetay.pas' {frmSatSiparisDetay},
  Ths.Erp.Database.Table.SatSiparisRapor in 'BackEnd\Erp\Sip\Ths.Erp.Database.Table.SatSiparisRapor.pas',
  ufrmSatSiparislerRapor in 'Forms\OutputForms\DbGrid\Erp\Sip\ufrmSatSiparislerRapor.pas' {frmSatSiparislerRapor},
  Ths.Erp.Database.Table.SetPrsAskerlikDurumu in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsAskerlikDurumu.pas',
  ufrmSetPrsAskerlikDurumlari in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsAskerlikDurumlari.pas' {frmSetPrsAskerlikDurumlari},
  ufrmSetPrsAskerlikDurumu in 'Forms\InputForms\Employee\ufrmSetPrsAskerlikDurumu.pas' {frmSetPrsAskerlikDurumu},
  Ths.Erp.Database.Table.SetPrsAyrilmaNedeni in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsAyrilmaNedeni.pas',
  ufrmSetPrsAyrilmaNedenleri in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsAyrilmaNedenleri.pas' {frmSetPrsAyrilmaNedenleri},
  ufrmSetPrsAyrilmaNedeni in 'Forms\InputForms\Employee\ufrmSetPrsAyrilmaNedeni.pas' {frmSetPrsAyrilmaNedeni},
  Ths.Erp.Database.Table.SetPrsBirim in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsBirim.pas',
  ufrmSetPrsBirimler in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsBirimler.pas' {frmSetPrsBirimler},
  ufrmSetPrsBirim in 'Forms\InputForms\Employee\ufrmSetPrsBirim.pas' {frmSetPrsBirim},
  Ths.Erp.Database.Table.SetPrsBolum in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsBolum.pas',
  ufrmSetPrsBolumler in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsBolumler.pas' {frmSetPrsBolumler},
  ufrmSetPrsBolum in 'Forms\InputForms\Employee\ufrmSetPrsBolum.pas' {frmSetPrsBolum},
  Ths.Erp.Database.Table.SetPrsCinsiyet in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsCinsiyet.pas',
  ufrmSetPrsCinsiyetler in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsCinsiyetler.pas' {frmSetPrsCinsiyetler},
  ufrmSetPrsCinsiyet in 'Forms\InputForms\Employee\ufrmSetPrsCinsiyet.pas' {frmSetPrsCinsiyet},
  Ths.Erp.Database.Table.SetPrsEgitimSeviyesi in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsEgitimSeviyesi.pas',
  ufrmSetPrsEgitimSeviyeleri in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsEgitimSeviyeleri.pas' {frmSetPrsEgitimSeviyeleri},
  ufrmSetPrsEgitimSeviyesi in 'Forms\InputForms\Employee\ufrmSetPrsEgitimSeviyesi.pas' {frmSetPrsEgitimSeviyesi},
  Ths.Erp.Database.Table.SetPrsEhliyet in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsEhliyet.pas',
  ufrmSetPrsEhliyetler in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsEhliyetler.pas' {frmSetPrsEhliyetler},
  ufrmSetPrsEhliyet in 'Forms\InputForms\Employee\ufrmSetPrsEhliyet.pas' {frmSetEmpDriverLicense},
  Ths.Erp.Database.Table.SetPrsGorev in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsGorev.pas',
  ufrmSetPrsGorevler in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsGorevler.pas' {frmSetPrsGorevler},
  ufrmSetPrsGorev in 'Forms\InputForms\Employee\ufrmSetPrsGorev.pas' {frmSetPrsGorev},
  Ths.Erp.Database.Table.SetPrsAyrilmaTipi in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsAyrilmaTipi.pas',
  ufrmSetPrsAyrilmaTipleri in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsAyrilmaTipleri.pas' {frmSetPrsAyrilmaTipleri},
  ufrmSetPrsAyrilmaTipi in 'Forms\InputForms\Employee\ufrmSetPrsAyrilmaTipi.pas' {frmSetPrsAyrilmaTipi},
  Ths.Erp.Database.Table.SetPrsMedeniDurum in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsMedeniDurum.pas',
  ufrmSetPrsMedeniDurumlar in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsMedeniDurumlar.pas' {frmSetPrsMedeniDurumlar},
  ufrmSetPrsMedeniDurum in 'Forms\InputForms\Employee\ufrmSetPrsMedeniDurum.pas' {frmSetPrsMedeniDurum},
  Ths.Erp.Database.Table.SetPrsMektupTipi in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsMektupTipi.pas',
  ufrmSetPrsMektupTipleri in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsMektupTipleri.pas' {frmSetPrsMektupTipleri},
  ufrmSetPrsMektupTipi in 'Forms\InputForms\Employee\ufrmSetPrsMektupTipi.pas' {frmSetPrsMektupTipi},
  Ths.Erp.Database.Table.SetPrsYeterlilikBelgesi in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsYeterlilikBelgesi.pas',
  ufrmSetPrsYeterlilikBelgeleri in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsYeterlilikBelgeleri.pas' {frmSetPrsYeterlilikBelgeleri},
  ufrmSetPrsYeterlilikBelgesi in 'Forms\InputForms\Employee\ufrmSetPrsYeterlilikBelgesi.pas' {frmSetPrsYeterlilikBelgesi},
  Ths.Erp.Database.Table.SetPrsPersonelTipi in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsPersonelTipi.pas',
  ufrmSetPrsPersonelTipleri in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsPersonelTipleri.pas' {frmSetPrsPersonelTipleri},
  ufrmSetPrsPersonelTipi in 'Forms\InputForms\Employee\ufrmSetPrsPersonelTipi.pas' {frmSetPrsPersonelTipi},
  Ths.Erp.Database.Table.SetPrsRaporTipi in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsRaporTipi.pas',
  ufrmSetPrsRaporTipleri in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsRaporTipleri.pas' {frmSetPrsRaporTipleri},
  ufrmSetPrsRaporTipi in 'Forms\InputForms\Employee\ufrmSetPrsRaporTipi.pas' {frmSetPrsRaporTipi},
  Ths.Erp.Database.Table.SetPrsSrcTipi in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsSrcTipi.pas',
  ufrmSetPrsSrcTipleri in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsSrcTipleri.pas' {frmSetPrsSrcTipleri},
  ufrmSetPrsSrcTipi in 'Forms\InputForms\Employee\ufrmSetPrsSrcTipi.pas' {frmSetPrsSrcTipi},
  Ths.Erp.Database.Table.SetPrsTatilTipi in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsTatilTipi.pas',
  ufrmSetPrsTatilTipleri in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsTatilTipleri.pas' {frmSetPrsTatilTipleri},
  ufrmSetPrsTatilTipi in 'Forms\InputForms\Employee\ufrmSetPrsTatilTipi.pas' {frmSetPrsTatilTipi},
  Ths.Erp.Database.Table.SetPrsLisan in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsLisan.pas',
  ufrmSetPrsLisanlar in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsLisanlar.pas' {frmSetPrsLisanlar},
  ufrmSetPrsLisan in 'Forms\InputForms\Employee\ufrmSetPrsLisan.pas' {frmSetPrsLisan},
  Ths.Erp.Database.Table.SetPrsLisanSeviyesi in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsLisanSeviyesi.pas',
  ufrmSetPrsLisanSeviyeleri in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsLisanSeviyeleri.pas' {frmSetPrsLisanSeviyeleri},
  ufrmSetPrsLisanSeviyesi in 'Forms\InputForms\Employee\ufrmSetPrsLisanSeviyesi.pas' {frmSetPrsLisanSeviyesi},
  Ths.Erp.Database.Table.SetPrsGecisSistemiKarti in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsGecisSistemiKarti.pas',
  ufrmSetPrsGecisSistemiKartlari in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsGecisSistemiKartlari.pas' {frmSetPrsGecisSistemiKartlari},
  ufrmSetPrsGecisSistemiKarti in 'Forms\InputForms\Employee\ufrmSetPrsGecisSistemiKarti.pas' {frmSetPrsGecisSistemiKarti},
  Ths.Erp.Database.Table.SetPrsServisAraci in 'BackEnd\Employee\Ths.Erp.Database.Table.SetPrsServisAraci.pas',
  ufrmSetPrsServisAraclari in 'Forms\OutputForms\DbGrid\Employee\ufrmSetPrsServisAraclari.pas' {frmSetPrsServisAraclari},
  ufrmSetPrsServisAraci in 'Forms\InputForms\Employee\ufrmSetPrsServisAraci.pas' {frmSetPrsServisAraci},
  Ths.Erp.Database.Table.PrsPersonel in 'BackEnd\Employee\Ths.Erp.Database.Table.PrsPersonel.pas',
  ufrmPrsPersoneller in 'Forms\OutputForms\DbGrid\Employee\ufrmPrsPersoneller.pas' {frmPrsPersoneller},
  ufrmPrsPersonel in 'Forms\InputForms\Employee\ufrmPrsPersonel.pas' {frmPrsPersonel},
  Ths.Erp.Database.Table.PrsPersonelGecmisi in 'BackEnd\Employee\Ths.Erp.Database.Table.PrsPersonelGecmisi.pas',
  Ths.Erp.Database.Table.PrsLisanBilgisi in 'BackEnd\Employee\Ths.Erp.Database.Table.PrsLisanBilgisi.pas',
  ufrmPrsLisanBilgileri in 'Forms\OutputForms\DbGrid\Employee\ufrmPrsLisanBilgileri.pas' {frmEmpLangAbilities},
  ufrmPrsLisanBilgisi in 'Forms\InputForms\Employee\ufrmPrsLisanBilgisi.pas' {frmEmpLangAbility},
  Ths.Erp.Database.Table.PrsEhliyetBilgisi in 'BackEnd\Employee\Ths.Erp.Database.Table.PrsEhliyetBilgisi.pas',
  ufrmPrsSrcBilgileri in 'Forms\OutputForms\DbGrid\Employee\ufrmPrsSrcBilgileri.pas' {frmEmpSrcAbilities},
  ufrmPrsSrcBilgisi in 'Forms\InputForms\Employee\ufrmPrsSrcBilgisi.pas' {frmEmpSrcAbility},
  Ths.Erp.Database.Table.PrsSrcBilgisi in 'BackEnd\Employee\Ths.Erp.Database.Table.PrsSrcBilgisi.pas',
  ufrmPrsEhliyetBilgileri in 'Forms\OutputForms\DbGrid\Employee\ufrmPrsEhliyetBilgileri.pas' {frmEmpDriverLicenseAbilities},
  ufrmPrsEhliyetBilgisi in 'Forms\InputForms\Employee\ufrmPrsEhliyetBilgisi.pas' {frmEmpDriverLicenseAbility},
  Ths.Erp.Database.Table.SetOdemeBaslangicDonemi in 'BackEnd\Erp\Ths.Erp.Database.Table.SetOdemeBaslangicDonemi.pas',
  ufrmSetOdemeBaslangicDonemleri in 'Forms\OutputForms\DbGrid\ufrmSetOdemeBaslangicDonemleri.pas' {frmSetOdemeBaslangicDonemleri},
  ufrmSetOdemeBaslangicDonemi in 'Forms\InputForms\ufrmSetOdemeBaslangicDonemi.pas' {frmSetOdemeBaslangicDonemi},
  ufrmTarihHaftaSecici in 'Forms\InputForms\Tools\ufrmTarihHaftaSecici.pas' {frmTarihHaftaSecici},
  Ths.Erp.Database.Table.SetBbkCalismaDurumu in 'BackEnd\BilgiBankasi\Ths.Erp.Database.Table.SetBbkCalismaDurumu.pas',
  ufrmSetBbkCalismaDurumlari in 'Forms\OutputForms\DbGrid\BilgiBankasi\ufrmSetBbkCalismaDurumlari.pas' {frmSetBbkCalismaDurumlari},
  ufrmSetBbkCalismaDurumu in 'Forms\InputForms\BilgiBankasi\ufrmSetBbkCalismaDurumu.pas' {frmSetBbkCalismaDurumu},
  Ths.Erp.Database.Table.SetBbkFinansDurumu in 'BackEnd\BilgiBankasi\Ths.Erp.Database.Table.SetBbkFinansDurumu.pas',
  ufrmSetBbkFinansDurumu in 'Forms\InputForms\BilgiBankasi\ufrmSetBbkFinansDurumu.pas' {frmSetBbkFinansDurumu},
  ufrmSetBbkFinansDurumlari in 'Forms\OutputForms\DbGrid\BilgiBankasi\ufrmSetBbkFinansDurumlari.pas' {frmSetBbkFinansDurumlari},
  Ths.Erp.Database.Table.SetBbkFirmaTipi in 'BackEnd\BilgiBankasi\Ths.Erp.Database.Table.SetBbkFirmaTipi.pas',
  ufrmSetBbkFirmaTipleri in 'Forms\OutputForms\DbGrid\BilgiBankasi\ufrmSetBbkFirmaTipleri.pas' {frmSetBbkFirmaTipleri},
  ufrmSetBbkFirmaTipi in 'Forms\InputForms\BilgiBankasi\ufrmSetBbkFirmaTipi.pas' {frmSetBbkFirmaTipi},
  Ths.Erp.Database.Table.BbkKayit in 'BackEnd\BilgiBankasi\Ths.Erp.Database.Table.BbkKayit.pas',
  ufrmBbkKayitlar in 'Forms\OutputForms\DbGrid\BilgiBankasi\ufrmBbkKayitlar.pas' {frmBbkKayitlar},
  ufrmBbkKayit in 'Forms\InputForms\BilgiBankasi\ufrmBbkKayit.pas' {frmBbkKayit},
  Ths.Erp.Database.Table.ChHesapHareketi in 'BackEnd\Erp\Ch\Ths.Erp.Database.Table.ChHesapHareketi.pas';

{$R *.res}

procedure MemLeakFix;
begin
  CheckSynchronize;
end;

begin
  Application.Initialize;
  Application.DefaultFont.Name := 'Tahoma';

  Application.UpdateFormatSettings := False;
  Formatsettings.ThousandSeparator := '.';
  Formatsettings.DecimalSeparator := ',';
  Formatsettings.DateSeparator := '.';
  Formatsettings.ShortDateFormat := 'dd.mm.yyyy';
  Formatsettings.LongDateFormat  := 'dd.mm.yyyy dddd';
  Formatsettings.ShortTimeFormat := 'HH:mm';
  Formatsettings.LongTimeFormat  := 'HH:mm:ss';
  Formatsettings.TimeSeparator   := ':';


{$WARN SYMBOL_PLATFORM OFF}
  {$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := {$IFDEF MSWINDOWS}DebugHook <> 0;{$ELSE}True;{$ENDIF MSWINDOWS}
  {$ENDIF}
{$WARN SYMBOL_PLATFORM ON}

  AddExitProc(MemLeakFix);

  Application.Title := 'THS ERP';
  Application.CreateForm(Tdm, dm);
  Application.CreateForm(TfrmMain, frmMain);
  if TfrmLogin.Execute then
  begin
    Application.ShowMainForm := True;
    Application.Run;
  end
  else
  begin
    Application.Terminate;
  end;
end.

